[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "build"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirect for shared conversations
[[redirects]]
  from = "/shared-conversation"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
